### ISSUE TITLE
The M521 lock works correctly, but 100% of the battery charge is constantly transmitted

### ISSUE THREAD

**Issue by VikeDragon** [formatBCE/Airbnk-MQTTOpenGateway#10]
Greetings!
The M521 lock works correctly, but 100% of the battery charge is constantly transmitted, even when the Where shows 35%. Please use the code to check the transmission of the battery level, because for the M521 it is necessary to track this props. The lock is reinforced and consumes a charge.
@ formatBCE thank you for such a wonderful job !

**Comment by formatBCE** [comment]
Hi @VikeDragon !

Yes, battery isn't good, on any of locks.
It's not a gateway that has to deal with it though. 
Gateway only transmits raw data to HA integration, and that's where data are parsed.
Please open ticket for @rospogrigio in main integration repo.

**Comment by VikeDragon** [comment]
Thank you ! Have a nice day!
