### ISSUE TITLE
RPi 4 Bluetooth 

### ISSUE THREAD

**Issue by mihaifireball** [formatBCE/Airbnk-MQTTOpenGateway#14]
It is not possible to use the build-in RPi 4 Bluetooth card as gateway?
I am using hassio on RPi 4.
Thanks!

**Comment by formatBCE** [comment]
Unfortunately, no.
The gateway isn't just Bluetooth - it's software, using Bluetooth only for communication with lock - then this data are communicated to/from HA integration. So someone would have to write this code.
