### ISSUE TITLE
Use ESP32 GPIO to close the lock

### ISSUE THREAD

**Issue by gorzynsk** [formatBCE/Airbnk-MQTTOpenGateway#2]
I would love to have a simple button to close the lock after leaving house. Would it be possible to add such functionality internally to your firmware?

I have autolock configured, but it often closes before second person leaves and she have to unlock it again. There's also a fear that autolock will not work and home stays open so I cannot really make the time to autolock longer. Hearing a lock working after pressing a button would solve all that.

**Comment by formatBCE** [comment]
Why wouldn't you use smart home possibilities for that?
Just hang Aqara button or similar thing - and done. :)

It's impossible to close the lock from gateway itself: payload for lock is generated by Home Assistant integration, not the ESP32.
So basically that button would still use WiFi to send request to HA - and this is achievable by any other button press
