### ISSUE TITLE
The gateway on the ESPHome firmware for M521 does not work

### ISSUE THREAD

**Issue by VikeDragon** [formatBCE/Airbnk-MQTTOpenGateway#5]
Greetings!
I installed the gateway via ESP Home in the recommended way. The device seems to be working, but probably does not see the lock M521. I checked the settings. 
Please help with the problem.
[logs_airbnk-gateway_logs.txt](https://github.com/formatBCE/Airbnk-MQTTOpenGateway/files/9635779/logs_airbnk-gateway_logs.txt)
[config_entry-esphome-ac4ab046b96c9b20ad89ab75c84cd7b8.json.txt](https://github.com/formatBCE/Airbnk-MQTTOpenGateway/files/9635785/config_entry-esphome-ac4ab046b96c9b20ad89ab75c84cd7b8.json.txt)

**Comment by formatBCE** [comment]
Hope you found the root cause.

**Comment by VikeDragon** [comment]
> Hope you found the root cause.

Yes, I found the problem - I brought the gateway closer to the bolt and it was fixed in Mqtt and integration. Thank you for your work! Very convenient with ESPHome!

**Comment by formatBCE** [comment]
If it will give you troubles - try to replace HA integration with my fork (it's not merged to main repo yet), and use another custom component for ESPHome - for me it's rock-solid for many days already.
Otherwise - enjoy!
