### ISSUE TITLE
Where to find MAC address

### ISSUE THREAD

**Issue by lightsabata** [formatBCE/Airbnk-MQTTOpenGateway#7]
Hi everybody
i try to use this solution to control my lock (MC501) from home assistant,
i have flashed the firmware on a ESP32 but on the confiruration page i cannot find the mac adress of my lock,
i've tried many bluetooth software on ios and windows to find it but with no succes (even en pairing mode) maybe it is because of BLE rules ? idk...
at last i stupidly throw the box i the trash and cannot retreive it

is anyone has a solution ?
thanks

**Comment by formatBCE** [comment]
Hi!

Do you happen to have Android device nearby? nRfConnect application is best in finding MAC. 
Another advise - when searching, try to be as close to the lock as possible. And make sure that you did setup the lock in WeHere app, and it's working already.

**Comment by lightsabata** [comment]
hi @formatBCE 
thank you for your quick response.
unfortunaltly i don't have android devices anymore...
the lock is already set up and working
i guss i'll have to find an android device then...

**Comment by formatBCE** [comment]
Uh, I don't have iOS at home...
Did you try https://apps.apple.com/us/app/ble-scanner-4-0/id1221763603 ? Seems to be okay...

**Comment by lightsabata** [comment]
yes this is the first app i have tried, it show many infos such as UUID, dB, etc.. but no mac adress...

**Comment by formatBCE** [comment]
So it found the lock, just not the mac address?

**Comment by lightsabata** [comment]
yes it found the lock (every app does) but no one shows the mac address, my the way with your fidt comment ihave foud nRf connect on ios appstore, even this one find bluetooth device but shows no mac adress (i really think it's a apple rule, but i'm not an expert)

**Comment by formatBCE** [comment]
Ooooh. Okay. So that's the problem...
Someone wrote, that iOS doesn't expose mac address: https://devzone.nordicsemi.com/f/nordic-q-a/74770/nrf-connect-ios

I guess you'll need Android, unfortunately...

And I will think on way to get MAC directly from gateway. It should be possible to do by scanning and checking device name...

**Comment by lightsabata** [comment]
thanks for your research.
i will find a friend who have an android
thanks !

**Comment by lightsabata** [comment]
@formatBCE think to add a function to get mac from the gateway in the futur
