### ISSUE TITLE
More locks to 1 espGateway

### ISSUE THREAD

**Issue by Corinake** [formatBCE/Airbnk-MQTTOpenGateway#9]
Hi, 
I want to add 1 more lock to the gateway.
I thing i need to add more MAC to config. But i don't know how much line need to add. Can you give me an example please?
Can i use same mqtt topic?
Thank you

**Comment by formatBCE** [comment]
Sorry, there's no possibility to connect several locks to same gateway. It's dictated by BLE restrictions: if simultaneous commands for several locks will be issued, gateway won't be able to process them, as radio stack isn't shareable.
